# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение всех товаров
GET {{baseUrl}}/products/
Content-Type: application/json

###

# получение конекретного товара
GET {{baseUrl}}/products/2
Content-Type: application/json

###

# создание товара
POST {{baseUrl}}/products/
Content-Type: application/json

{
    "category": 1,
    "model": "apple/iphone/xs-max",
    "name": "Смартфон Apple iPhone XS Max 512GB (золотистый)",
    "price": 1100200,
    "price_rrc": 1126990,
    "quantity": 14,
    "description": "Познакомьтесь с iPhone XS 512 ГБ в золотом цвете в Apple Store — элегантный дизайн, высокая производительность и потрясающий Super Retina дисплей. Премиум-смартфон для тех, кто ценит лучшее!",
    "parameters": {
        "Диагональ (дюйм)": "6.5",
        "Разрешение (пикс)": "2688x1242",
        "Встроенная память (Гб)": "512",
        "Цвет": "золотистый"
    },
    "shop_name": "Apple"
}

###

# обновление характеристик товара
PATCH {{baseUrl}}/products/15/
Content-Type: application/json

{
  "price": 110000,
  "price_rrc": 120000,
  "description": "Откройте для себя iPhone 15 в Apple Store — стильный дизайн, мощная производительность и передовые функции, такие как чип A17 и улучшенная камера. Поднимите свой мобильный опыт на новый уровень!",
  "parameters": {
    "Встроенная память (Гб)": "512"
  }
}

###

# удаление товара
DELETE {{baseUrl}}/products/1/
Content-Type: application/json


###