# примеры API-запросов

@baseUrl = http://localhost:8000

# получение всех товаров
GET {{baseUrl}}/products/
Content-Type: application/json

###

# получение конекретного товара
GET {{baseUrl}}/products/2
Content-Type: application/json

###

# создание товара
POST {{baseUrl}}/products/
Content-Type: application/json

{
    "category": 1,
    "model": "apple/iphone/xs-max",
    "name": "Смартфон Apple iPhone XS Max 512GB (золотистый)",
    "price": 1100200,
    "price_rrc": 1126990,
    "quantity": 14,
    "description": "Познакомьтесь с iPhone XS 512 ГБ в золотом цвете в Apple Store — элегантный дизайн, высокая производительность и потрясающий Super Retina дисплей. Премиум-смартфон для тех, кто ценит лучшее!",
    "parameters": {
        "Диагональ (дюйм)": "6.5",
        "Разрешение (пикс)": "2688x1242",
        "Встроенная память (Гб)": "512",
        "Цвет": "золотистый"
    },
    "shop_name": "Apple"
}

###

# обновление характеристик товара
PATCH {{baseUrl}}/products/15/
Content-Type: application/json

{
  "price": 110000,
  "price_rrc": 120000,
  "description": "Откройте для себя iPhone 15 в Apple Store — стильный дизайн, мощная производительность и передовые функции, такие как чип A17 и улучшенная камера. Поднимите свой мобильный опыт на новый уровень!",
  "parameters": {
    "Встроенная память (Гб)": "512"
  }
}

###

# удаление товара
DELETE {{baseUrl}}/products/3/
Content-Type: application/json

###

# получение cписка пользователей
GET {{baseUrl}}/users/
Content-Type: application/json

###

# получение информации о пользователе
GET {{baseUrl}}/users/1
Content-Type: application/json

###

# получение контактной информации пользователя
GET {{baseUrl}}/users/1/contacts/
Content-Type: application/json

###

# получение контактной информации пользователя
# (у пользователя может быть больше 1 адреса доставки)
GET {{baseUrl}}/users/1/contacts/3
Content-Type: application/json


###

# отправка письма пользователю
POST {{baseUrl}}/confirm/
Content-Type: application/json

{
  "user_email": "jkeevk@yandex.ru",
  "user_name": "Сергей",
  "order_details": "Заказ номер 1 сформирован"
}

###

# команды на обновление товаров поставщиков через консоль
curl -X POST -F "file=@/Users/sergeyigumnov/Desktop/VS Code/Netology/diploma_shop/data/shop1.json" http://localhost:8000/api/partner/update
# вручную
python manage.py load_products data/shop1.json

###

# обновление товаров поставщиков
POST {{baseUrl}}/partner/update
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="shop1.json"
Content-Type: application/json

< /Users/sergeyigumnov/Desktop/VS Code/Netology/diploma_shop/data/shop1.json
--MyBoundary--


###

# аутентификация
POST {{baseUrl}}/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "shop@admin.com",
    "password": "shop"
}

###

# регистрация
POST {{baseUrl}}/user/register/
Content-Type: application/json

{
    "username": "xddd",
    "email": "admin2d2@example.com",
    "password": "admidn12!",
    "is_customer": true,
    "is_supplier": false
}


eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNDk3MDc1LCJpYXQiOjE3Mzk4OTcwNzUsImp0aSI6IjYxYWVlYTEyNmVmZjQwYmU4ZDk3YTJmMjY1ZThiNWIwIiwidXNlcl9pZCI6MX0.iyiTjfK1mCrfhuokxrYKZdZCAHy_OPglQ8rVV2Ndavc

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTA0Nzk1LCJpYXQiOjE3Mzk5MDQ3OTUsImp0aSI6IjBiMjhhYjA4OGNhYTQwOWNhYjEzZTZkY2YyY2MyMzdhIiwidXNlcl9pZCI6MX0.tR0y1oVt4D8fi91t2GjNwSTfyAs117h5Uxg2MIvw9Kc