# Generated by Django 5.1.4 on 2025-02-19 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_contact_options_remove_contact_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price_rrc',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Рекомендуемая розничная цена'),
        ),
    ]
