# Generated by Django 5.1.4 on 2025-02-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productparameter',
            unique_together={('product_info', 'parameter', 'value')},
        ),
    ]
