name: Coverage
on:
  pull_request:
    branches: [main, master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - Check coverage.xml
        run: |
          ls -la ./coverage/

      - name: Generate coverage badge
        id: badge
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: ./coverage/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create badges directory
        run: |
          mkdir -p badges

      - name: Check if badge was generated
        run: |
          if [ -f coverage.svg ]; then
            mv coverage.svg badges/coverage.svg
          else
            echo "Badge not generated"
          fi

      - name: Commit and push badge
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add badges/coverage.svg || echo "No badge to add"
          git commit -m "Update coverage badge" || echo "No changes"
          git push