name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage coverage-badge

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage xml

      - name: Debug - List files in coverage directory
        run: ls -la coverage/

      - name: Generate badge
        run: |
          coverage-badge -f coverage/coverage.xml -o badges/coverage.svg

      - name: Debug - List files in badges directory
        run: ls -la badges/